package com.adventofcode;

import java.util.*;

public class d6t1 {

    public static void main(String[] args) {

        String input = "PJK)X3G\n" +
                "ZM3)JGN\n" +
                "YYF)614\n" +
                "K5T)X18\n" +
                "2PT)2BR\n" +
                "4RF)VL2\n" +
                "QQN)7S4\n" +
                "X9S)HM9\n" +
                "NMG)DH5\n" +
                "TQD)SJD\n" +
                "2JD)SM4\n" +
                "5SD)4NG\n" +
                "W1R)XYJ\n" +
                "DXF)72L\n" +
                "CGN)T85\n" +
                "ZF4)ZZ1\n" +
                "91Q)Y69\n" +
                "SMB)QSZ\n" +
                "PVN)PP3\n" +
                "C4S)1VL\n" +
                "3BK)ZNZ\n" +
                "LYZ)92X\n" +
                "TPP)XPP\n" +
                "NTK)R7B\n" +
                "XMH)GBQ\n" +
                "LZW)49Y\n" +
                "28R)R1G\n" +
                "5SX)F2K\n" +
                "X21)WC7\n" +
                "JL7)ZKL\n" +
                "F1G)XF8\n" +
                "XJG)N8L\n" +
                "227)HBK\n" +
                "FG8)RMS\n" +
                "S5B)RXD\n" +
                "T71)LDZ\n" +
                "TYQ)2LW\n" +
                "1W2)BFQ\n" +
                "2X1)NCQ\n" +
                "SJL)TG5\n" +
                "64W)RKB\n" +
                "DRH)W45\n" +
                "ZTK)YC5\n" +
                "L1Y)VXS\n" +
                "SGD)F66\n" +
                "ZBG)YJ7\n" +
                "NC6)544\n" +
                "XKQ)8Z5\n" +
                "B5K)XFW\n" +
                "V3F)SF9\n" +
                "DC7)737\n" +
                "ZCJ)ZCB\n" +
                "JPX)FZS\n" +
                "PFB)TYQ\n" +
                "C22)HGM\n" +
                "C67)MDM\n" +
                "4W1)X87\n" +
                "TQX)7YM\n" +
                "2Y4)CLQ\n" +
                "R1G)M5V\n" +
                "HK5)56W\n" +
                "Y7B)8RN\n" +
                "LFR)FN6\n" +
                "RVW)7G3\n" +
                "SXH)97Y\n" +
                "H25)WHC\n" +
                "X8Y)3H8\n" +
                "97Y)77T\n" +
                "6VB)91Q\n" +
                "V7S)595\n" +
                "JFH)2JD\n" +
                "ZSL)HHS\n" +
                "3D6)T71\n" +
                "1BP)MCR\n" +
                "FBQ)2PB\n" +
                "7Q9)K1X\n" +
                "C81)6JF\n" +
                "YYQ)9FR\n" +
                "FBR)GZS\n" +
                "VXK)4BR\n" +
                "Z9L)DYJ\n" +
                "PRL)K2Y\n" +
                "Q68)R8F\n" +
                "WJC)WZ5\n" +
                "H3K)3NG\n" +
                "K9N)BG4\n" +
                "VXS)RLT\n" +
                "K1Q)R29\n" +
                "C76)TNL\n" +
                "RLV)PCY\n" +
                "Z4J)2GC\n" +
                "4F2)SC2\n" +
                "Y82)JKM\n" +
                "GZS)Q1Q\n" +
                "VB3)WRW\n" +
                "XW6)FK8\n" +
                "YG1)73H\n" +
                "KZQ)9FQ\n" +
                "R25)C13\n" +
                "FFZ)DTC\n" +
                "H99)Y82\n" +
                "N12)TRX\n" +
                "F5G)RLV\n" +
                "7VN)D7V\n" +
                "CRJ)GY4\n" +
                "C7S)YD3\n" +
                "V6S)CNH\n" +
                "82G)ZBV\n" +
                "KMM)YOU\n" +
                "27R)S8P\n" +
                "ZTK)2PT\n" +
                "8R4)HC5\n" +
                "V9D)ZSV\n" +
                "L25)N12\n" +
                "544)ZT7\n" +
                "62H)SBL\n" +
                "ZMG)M4P\n" +
                "Y77)SB7\n" +
                "G6R)2RZ\n" +
                "YPB)6ZG\n" +
                "WKT)FVM\n" +
                "126)ZPY\n" +
                "8KQ)KSF\n" +
                "G3Q)W3D\n" +
                "56F)RZX\n" +
                "KFC)LHG\n" +
                "75Y)BHL\n" +
                "921)95L\n" +
                "QRQ)SG4\n" +
                "8BW)KGK\n" +
                "5D5)YH2\n" +
                "4PK)9LQ\n" +
                "7J4)QQN\n" +
                "F8Q)SBM\n" +
                "14K)5NV\n" +
                "6NP)91L\n" +
                "JKM)HR1\n" +
                "9G9)Q7P\n" +
                "P74)BCK\n" +
                "DBC)K1H\n" +
                "CH7)Z9W\n" +
                "GBK)YFR\n" +
                "LLX)YG1\n" +
                "KFB)C53\n" +
                "7XJ)8Q8\n" +
                "54L)JMG\n" +
                "2PB)P2C\n" +
                "ZPY)V3S\n" +
                "NG6)WNM\n" +
                "R29)LN8\n" +
                "1DT)LTD\n" +
                "XLM)X12\n" +
                "3HQ)G3Q\n" +
                "95L)VM4\n" +
                "8RN)Q28\n" +
                "2GC)CVB\n" +
                "BHL)N5T\n" +
                "X9T)GBK\n" +
                "J27)G8G\n" +
                "LHG)RR3\n" +
                "FS5)XSF\n" +
                "6HN)WC8\n" +
                "WQR)G1C\n" +
                "X5M)SXQ\n" +
                "MCR)Q6W\n" +
                "F57)7W8\n" +
                "QKG)X4T\n" +
                "PL8)BZM\n" +
                "JM3)3KS\n" +
                "GYP)6S2\n" +
                "8V3)4TV\n" +
                "GSV)Y9V\n" +
                "JKM)5WX\n" +
                "VSM)3Q5\n" +
                "L7Q)L1C\n" +
                "MFX)T1R\n" +
                "GQ2)22M\n" +
                "4L4)W3W\n" +
                "TRX)45N\n" +
                "GLG)WKT\n" +
                "92T)KTL\n" +
                "1PB)TFX\n" +
                "C9N)88W\n" +
                "Z19)PTB\n" +
                "95K)NGQ\n" +
                "8H6)CHW\n" +
                "DC8)7NY\n" +
                "R8F)HHP\n" +
                "TFX)S9L\n" +
                "P61)4JD\n" +
                "KDW)GMS\n" +
                "961)J5R\n" +
                "C4H)35Y\n" +
                "BJQ)FDN\n" +
                "R79)P6J\n" +
                "QTH)B6J\n" +
                "K2Y)3RY\n" +
                "K47)NC6\n" +
                "GQR)C5W\n" +
                "6HN)LLX\n" +
                "Q7P)921\n" +
                "WPV)VLF\n" +
                "329)YPB\n" +
                "3XV)RR1\n" +
                "DTC)2CF\n" +
                "C9K)X43\n" +
                "5SB)X9T\n" +
                "9ZL)8V3\n" +
                "F5G)XMH\n" +
                "VD5)XG2\n" +
                "97R)SC9\n" +
                "NCQ)F2D\n" +
                "BML)2JY\n" +
                "N8G)DMN\n" +
                "6Y7)JXB\n" +
                "M4P)Z4J\n" +
                "PL1)M52\n" +
                "57Z)HSB\n" +
                "LP8)WXJ\n" +
                "X49)ZHJ\n" +
                "YQ4)LBF\n" +
                "TZN)26G\n" +
                "3NG)PLN\n" +
                "XLC)TBR\n" +
                "8ZV)77G\n" +
                "3SR)QR2\n" +
                "91B)J7Y\n" +
                "PWH)LJS\n" +
                "GG3)91S\n" +
                "2NJ)C23\n" +
                "MRG)V2D\n" +
                "77G)NBP\n" +
                "DBC)3N2\n" +
                "Q1Q)Z34\n" +
                "BH4)B5K\n" +
                "V5P)8Q7\n" +
                "35Y)39W\n" +
                "DMN)DKJ\n" +
                "GY4)HPQ\n" +
                "66L)S4M\n" +
                "FK8)W9R\n" +
                "W3W)X5M\n" +
                "YBW)X41\n" +
                "WPG)XQN\n" +
                "BKC)NBD\n" +
                "82C)8ZV\n" +
                "8LR)P74\n" +
                "XL9)F17\n" +
                "DKJ)V6X\n" +
                "836)FFB\n" +
                "RS8)K1Q\n" +
                "CY5)4PC\n" +
                "YFR)GTQ\n" +
                "QF6)ZLD\n" +
                "35K)5YW\n" +
                "P6J)Z8W\n" +
                "Z39)NJK\n" +
                "J8X)T8P\n" +
                "15H)YXX\n" +
                "K5M)3B4\n" +
                "FVY)L93\n" +
                "DS2)QP5\n" +
                "39W)WTS\n" +
                "NFM)LFR\n" +
                "4ZR)N8K\n" +
                "JGW)4XY\n" +
                "XSP)9YR\n" +
                "5WB)286\n" +
                "292)637\n" +
                "KTL)3CT\n" +
                "TQR)GPW\n" +
                "ZT7)7H2\n" +
                "6YX)VCC\n" +
                "G2X)HLX\n" +
                "7QT)33M\n" +
                "SXQ)6VY\n" +
                "1WQ)ZMG\n" +
                "G1C)35K\n" +
                "D7V)PZG\n" +
                "73H)NG6\n" +
                "TQD)6M6\n" +
                "GPW)YQ4\n" +
                "C67)C4H\n" +
                "G6F)9YS\n" +
                "YLZ)YBW\n" +
                "4XZ)KSG\n" +
                "11N)V9D\n" +
                "56W)8R4\n" +
                "S8P)PVN\n" +
                "XG2)Z7K\n" +
                "LBF)6KM\n" +
                "ZSV)VF3\n" +
                "QV6)JJN\n" +
                "2D9)VM8\n" +
                "TYB)NTG\n" +
                "Q94)QNF\n" +
                "4JD)J8X\n" +
                "5WB)MVZ\n" +
                "X12)KV2\n" +
                "79V)VP8\n" +
                "8VV)B6R\n" +
                "T42)8BW\n" +
                "C13)Z9L\n" +
                "WFY)HC7\n" +
                "3LK)RV9\n" +
                "6LP)W98\n" +
                "6LD)XLM\n" +
                "YBQ)GQ2\n" +
                "VF3)MLX\n" +
                "DQ7)66L\n" +
                "C53)5F1\n" +
                "5F1)YZY\n" +
                "3GQ)C67\n" +
                "M52)VWY\n" +
                "M89)9L5\n" +
                "HPQ)4W1\n" +
                "8Z5)7FX\n" +
                "F8Q)1TY\n" +
                "4FC)VN3\n" +
                "2DG)PL1\n" +
                "KT2)7QT\n" +
                "X3G)GH2\n" +
                "VFH)5ZL\n" +
                "3SN)ZW3\n" +
                "RTP)1KS\n" +
                "KGK)2NJ\n" +
                "8Z5)F57\n" +
                "91S)DC7\n" +
                "SLY)QBX\n" +
                "BKH)M89\n" +
                "637)6FC\n" +
                "V7K)L25\n" +
                "QCF)Q3X\n" +
                "4L1)X58\n" +
                "B2S)J5L\n" +
                "JJK)6PN\n" +
                "F4V)MHH\n" +
                "SC4)34G\n" +
                "5XC)GPJ\n" +
                "PTB)579\n" +
                "C3D)XCK\n" +
                "HDY)PCH\n" +
                "KTM)8XY\n" +
                "3KS)GYP\n" +
                "HHS)RD2\n" +
                "68B)YBQ\n" +
                "L1C)7C7\n" +
                "TKK)NWD\n" +
                "YD3)JKC\n" +
                "VM8)38W\n" +
                "S9X)H3K\n" +
                "VN3)WPG\n" +
                "2RZ)56F\n" +
                "PG2)Z3G\n" +
                "SJD)SKH\n" +
                "JKC)XJG\n" +
                "KTK)V6B\n" +
                "Z7L)64W\n" +
                "6KS)GR6\n" +
                "BZM)6NP\n" +
                "HSB)2T3\n" +
                "YC5)5WB\n" +
                "6RL)PFB\n" +
                "TL2)XSP\n" +
                "8NL)VV7\n" +
                "KZH)3BK\n" +
                "FN6)FG8\n" +
                "NQ6)YWV\n" +
                "4K3)WFZ\n" +
                "4VT)SZH\n" +
                "7C7)JKB\n" +
                "FJJ)WP9\n" +
                "FBZ)QRQ\n" +
                "88W)RD6\n" +
                "GPH)5VZ\n" +
                "F17)7FJ\n" +
                "VWY)TWJ\n" +
                "BRN)95K\n" +
                "R55)LP8\n" +
                "9K3)M4B\n" +
                "NWD)JSX\n" +
                "4NS)783\n" +
                "6VH)D6T\n" +
                "XYQ)BHN\n" +
                "3RY)MFX\n" +
                "KGR)QGX\n" +
                "1XH)MNS\n" +
                "1TY)15L\n" +
                "XWV)WJC\n" +
                "JJN)8B3\n" +
                "Y8L)Y7B\n" +
                "FFQ)3SG\n" +
                "F77)Z5Z\n" +
                "783)Q9R\n" +
                "HF2)RMK\n" +
                "WRW)JT4\n" +
                "6MS)FBQ\n" +
                "44G)BRN\n" +
                "FDN)289\n" +
                "4NJ)ZF6\n" +
                "WN8)Y77\n" +
                "66G)FMH\n" +
                "773)7HJ\n" +
                "M4B)Z7L\n" +
                "V88)52G\n" +
                "2HR)24V\n" +
                "3KH)VYY\n" +
                "77T)PG2\n" +
                "S8N)G6F\n" +
                "QY2)54G\n" +
                "F66)9KL\n" +
                "FLB)SFB\n" +
                "HLX)32D\n" +
                "S4M)VXK\n" +
                "XPP)DQ7\n" +
                "3SG)BH4\n" +
                "Z5S)XW6\n" +
                "92X)XLC\n" +
                "LQ4)3GQ\n" +
                "729)PRL\n" +
                "S3N)Z5S\n" +
                "29B)K47\n" +
                "WBQ)TKK\n" +
                "BJR)GC5\n" +
                "Y82)ZM3\n" +
                "GK1)62H\n" +
                "8Q7)ZR3\n" +
                "7YM)7Q9\n" +
                "4R4)FQ7\n" +
                "B6V)2HR\n" +
                "T95)LQ4\n" +
                "T99)6SL\n" +
                "COM)ZB8\n" +
                "4SC)SMZ\n" +
                "X87)GX6\n" +
                "ZKL)M72\n" +
                "7W8)WN8\n" +
                "64G)15F\n" +
                "34G)K9J\n" +
                "BSK)2MM\n" +
                "1ZV)4FC\n" +
                "Z5Z)CZC\n" +
                "LKS)N8G\n" +
                "XDC)P5D\n" +
                "RXD)B9R\n" +
                "2BR)BKC\n" +
                "HHP)85J\n" +
                "QX7)FWL\n" +
                "WTS)WBQ\n" +
                "ZLY)6T5\n" +
                "LP9)G65\n" +
                "9ZL)GG2\n" +
                "4JY)2FH\n" +
                "QJZ)384\n" +
                "6S2)ZLY\n" +
                "2W1)XL9\n" +
                "X4T)LKB\n" +
                "38W)2YD\n" +
                "RZX)NL6\n" +
                "2BW)ZF4\n" +
                "K6L)24D\n" +
                "TZM)SGD\n" +
                "2JY)K5T\n" +
                "MP9)GLG\n" +
                "8VV)TQX\n" +
                "MQJ)G2B\n" +
                "W9R)Y8L\n" +
                "6Y8)8NR\n" +
                "CNH)2X1\n" +
                "5Y4)QKG\n" +
                "TWJ)V7S\n" +
                "CNJ)9K3\n" +
                "5VZ)YYF\n" +
                "48Q)4L1\n" +
                "1VL)2W1\n" +
                "HSB)VC9\n" +
                "HKT)45Z\n" +
                "CP6)XY1\n" +
                "JKC)GM1\n" +
                "B1H)D6Q\n" +
                "4B9)8XW\n" +
                "DLX)15H\n" +
                "45Z)HNQ\n" +
                "289)75Y\n" +
                "2MM)GCH\n" +
                "NBD)FFZ\n" +
                "QGX)Q3V\n" +
                "N1F)9G9\n" +
                "P54)P9L\n" +
                "GC5)62Z\n" +
                "15L)11N\n" +
                "TK1)CCW\n" +
                "35W)8S3\n" +
                "4NG)4FZ\n" +
                "1P9)MND\n" +
                "5ZL)FVY\n" +
                "L5P)79V\n" +
                "VCC)WPV\n" +
                "8BG)9M4\n" +
                "24V)T95\n" +
                "YFR)F1G\n" +
                "FS5)H1M\n" +
                "JKB)YVS\n" +
                "N1K)7NP\n" +
                "LKR)S82\n" +
                "SLY)7R3\n" +
                "GTQ)L2N\n" +
                "L2N)4DJ\n" +
                "CGN)7S9\n" +
                "NJ7)7QH\n" +
                "WXB)KT2\n" +
                "R3T)78Q\n" +
                "XSF)QCF\n" +
                "T85)1W2\n" +
                "11N)29B\n" +
                "6SL)BQ2\n" +
                "1Y2)C81\n" +
                "B6J)5XC\n" +
                "GV4)LW1\n" +
                "FFB)1WQ\n" +
                "GPP)6LP\n" +
                "FYL)4R4\n" +
                "K9N)KZQ\n" +
                "ZB8)RRS\n" +
                "YP6)Q68\n" +
                "9FQ)1PB\n" +
                "7G3)2L3\n" +
                "KJK)NYV\n" +
                "WNM)9ZL\n" +
                "JMZ)QF6\n" +
                "38S)44G\n" +
                "JG6)LYZ\n" +
                "286)WXS\n" +
                "B4B)Y8Y\n" +
                "ZML)VRJ\n" +
                "Z2X)FVK\n" +
                "TNS)8BG\n" +
                "8S3)QLD\n" +
                "NBP)DRH\n" +
                "TKL)429\n" +
                "CC7)9DN\n" +
                "FYL)14D\n" +
                "LLX)3SZ\n" +
                "QQX)WF9\n" +
                "LJS)GMZ\n" +
                "7R3)2WR\n" +
                "4GT)4F2\n" +
                "9LQ)DBC\n" +
                "YPZ)4GT\n" +
                "9BK)SMB\n" +
                "QB9)P4L\n" +
                "3N2)ZQ9\n" +
                "7N8)F7L\n" +
                "BLG)B2S\n" +
                "1SF)W53\n" +
                "ZZ1)4B9\n" +
                "H4Q)KJK\n" +
                "ZXN)4SC\n" +
                "82C)8D8\n" +
                "15F)KGR\n" +
                "54G)XXH\n" +
                "J7Y)QJZ\n" +
                "SNM)SXH\n" +
                "BKH)8VV\n" +
                "SMB)KTK\n" +
                "ZS2)2KV\n" +
                "L2N)C76\n" +
                "Q1T)BJQ\n" +
                "GQR)SK6\n" +
                "QQK)TGL\n" +
                "LW1)FLB\n" +
                "3B4)J6L\n" +
                "V6B)57Z\n" +
                "Y1R)2DG\n" +
                "QQH)Z2Q\n" +
                "G8G)8KQ\n" +
                "8NR)K9N\n" +
                "6M6)3KH\n" +
                "J27)28R\n" +
                "85J)48Q\n" +
                "RLT)LKR\n" +
                "XY1)CGN\n" +
                "ZW3)N1K\n" +
                "QR2)6LD\n" +
                "88G)G6R\n" +
                "QGY)126\n" +
                "5XC)X9S\n" +
                "X5N)7VN\n" +
                "8D8)97R\n" +
                "PYX)KMM\n" +
                "N8K)7B8\n" +
                "MF9)PXY\n" +
                "8WW)4NS\n" +
                "JZ8)RVW\n" +
                "H1M)78C\n" +
                "QZV)3XV\n" +
                "YZY)66Z\n" +
                "WFZ)44F\n" +
                "3Q5)PPH\n" +
                "NTG)SNM\n" +
                "HBK)CM6\n" +
                "6JF)CH7\n" +
                "CVB)Y9X\n" +
                "F5G)TZN\n" +
                "95K)Y1R\n" +
                "614)54L\n" +
                "TPP)66G\n" +
                "4BR)8WW\n" +
                "YJ7)W1R\n" +
                "Q9R)773\n" +
                "YH2)SY4\n" +
                "2CF)3Q6\n" +
                "GK1)NPV\n" +
                "6PL)TL2\n" +
                "6RQ)X5N\n" +
                "TGK)52W\n" +
                "7HJ)SC4\n" +
                "7B8)L8S\n" +
                "MKR)88G\n" +
                "SC2)DLX\n" +
                "SF9)KFC\n" +
                "QSZ)KBD\n" +
                "VL2)S9X\n" +
                "LV6)HK5\n" +
                "FMJ)8R2\n" +
                "9YR)YLZ\n" +
                "N23)V3F\n" +
                "B6R)DXF\n" +
                "M5V)KZH\n" +
                "6VY)CRW\n" +
                "T3Z)MQJ\n" +
                "JVM)WFJ\n" +
                "33M)9G7\n" +
                "W45)VFH\n" +
                "YZY)1LY\n" +
                "HR1)QF5\n" +
                "JGN)QB9\n" +
                "991)F5G\n" +
                "78C)J27\n" +
                "8XW)5SB\n" +
                "BHN)4SY\n" +
                "LKB)BSK\n" +
                "3DL)GQR\n" +
                "9XC)B6V\n" +
                "L4C)PD6\n" +
                "LN8)82C\n" +
                "P2C)Z19\n" +
                "SNM)C3D\n" +
                "4SY)8NL\n" +
                "8Q8)4RF\n" +
                "QLD)NS6\n" +
                "C7M)6HN\n" +
                "PZG)TBV\n" +
                "D6T)KFB\n" +
                "DYJ)TLH\n" +
                "PQJ)729\n" +
                "Z7K)QQK\n" +
                "ZLD)Q49\n" +
                "JT4)6PL\n" +
                "49Y)WZ9\n" +
                "X43)VNS\n" +
                "3SZ)H25\n" +
                "ZF6)QGY\n" +
                "SCD)FMJ\n" +
                "6FC)RTP\n" +
                "RMS)GZC\n" +
                "VNS)961\n" +
                "Z2Q)NJ7\n" +
                "H3K)9XC\n" +
                "9J3)6VB\n" +
                "BRN)3HQ\n" +
                "NQY)GTK\n" +
                "D8W)F6F\n" +
                "GMS)LXG\n" +
                "L5Y)B1H\n" +
                "HC5)KTM\n" +
                "QVC)292\n" +
                "MCN)G2X\n" +
                "HC7)TNW\n" +
                "QBX)1XH\n" +
                "X1H)X5D\n" +
                "NPV)SLY\n" +
                "DYN)VD5\n" +
                "CCW)7CP\n" +
                "TG5)6Y7\n" +
                "6PL)CYJ\n" +
                "2LW)8H9\n" +
                "77T)ZXN\n" +
                "X5D)HJ2\n" +
                "S82)2BW\n" +
                "729)PL8\n" +
                "Y9V)8MW\n" +
                "PCH)LZW\n" +
                "XQN)3SN\n" +
                "WC7)ZML\n" +
                "V3S)JJK\n" +
                "T46)XG7\n" +
                "XF4)TPP\n" +
                "SH8)2Y4\n" +
                "WXT)892\n" +
                "P9L)V6S\n" +
                "PXY)JG4\n" +
                "CY5)MF9\n" +
                "X41)NQ6\n" +
                "B9R)9HH\n" +
                "M4P)91B\n" +
                "RD6)QQ4\n" +
                "SMZ)X49\n" +
                "4DJ)BKH\n" +
                "D6Q)F8Q\n" +
                "ZHJ)4ZZ\n" +
                "MDM)QXG\n" +
                "RMK)B5Z\n" +
                "27F)1Y2\n" +
                "J87)Z39\n" +
                "G65)5Y4\n" +
                "NGQ)LP9\n" +
                "Z34)MP9\n" +
                "VLN)YPZ\n" +
                "MHH)K6L\n" +
                "F7L)JZ8\n" +
                "9KL)8LZ\n" +
                "5XS)TK1\n" +
                "MNS)Z2X\n" +
                "2KZ)K5M\n" +
                "CZC)8LR\n" +
                "RS8)7XJ\n" +
                "M72)VHV\n" +
                "6PN)TKL\n" +
                "SG4)FBR\n" +
                "SC9)5WZ\n" +
                "N8L)ZTK\n" +
                "XG7)MKK\n" +
                "KB9)JL7\n" +
                "1GQ)82G\n" +
                "N4X)91W\n" +
                "F6F)NR4\n" +
                "44F)1SF\n" +
                "SZH)CNJ\n" +
                "V2D)F7M\n" +
                "Y77)RS8\n" +
                "VD3)7P7\n" +
                "LXG)S5B\n" +
                "QXG)KDW\n" +
                "2KV)T46\n" +
                "XXJ)1BP\n" +
                "ZNZ)MBB\n" +
                "BG4)Q94\n" +
                "B5Z)CVD\n" +
                "5WZ)T8K\n" +
                "2MM)FLH\n" +
                "CHW)V88\n" +
                "FZS)DS2\n" +
                "WZ5)LDJ\n" +
                "BFQ)MKR\n" +
                "Y1R)YLV\n" +
                "QLD)34L\n" +
                "737)GPH\n" +
                "QQX)1ZV\n" +
                "CRW)T42\n" +
                "73H)L9K\n" +
                "G2B)VJV\n" +
                "9G7)SH8\n" +
                "Z3G)T3Z\n" +
                "9YS)TGK\n" +
                "7NY)27R\n" +
                "8R2)WXT\n" +
                "GPH)FS5\n" +
                "KBD)7N8\n" +
                "HM9)68B\n" +
                "2YD)PD5\n" +
                "9YS)38S\n" +
                "Z8W)W8Z\n" +
                "3KH)X4V\n" +
                "6ZG)935\n" +
                "36T)QX7\n" +
                "9L5)SPK\n" +
                "VLF)4L4\n" +
                "XCK)GPP\n" +
                "66Z)FFQ\n" +
                "XXH)H4Q\n" +
                "FWL)TQD\n" +
                "9DN)YYQ\n" +
                "F7M)4XZ\n" +
                "7S4)BML\n" +
                "L58)FCC\n" +
                "739)XWV\n" +
                "YQ4)FJJ\n" +
                "3CT)JM3\n" +
                "KSG)NMG\n" +
                "6T5)JG6\n" +
                "T8K)X8Y\n" +
                "K6L)QQH\n" +
                "P74)9HY\n" +
                "JG4)9BK\n" +
                "9FR)836\n" +
                "TNW)6RL\n" +
                "RR3)HD6\n" +
                "26G)SCD\n" +
                "HC5)B98\n" +
                "72L)6G9\n" +
                "6G9)1DT\n" +
                "32D)FBZ\n" +
                "1TY)C7S\n" +
                "QQ4)43D\n" +
                "RV9)5D5\n" +
                "7P7)MCN\n" +
                "5YW)6YX\n" +
                "S99)6RQ\n" +
                "RR1)YBD\n" +
                "V6X)227\n" +
                "SBL)6Y8\n" +
                "6KM)X21\n" +
                "66Y)4VT\n" +
                "91L)4PK\n" +
                "PD5)4K3\n" +
                "Y8Y)L1Y\n" +
                "LHS)L4C\n" +
                "1LY)SAN\n" +
                "W8Z)L5Y\n" +
                "V6X)KS8\n" +
                "7FX)J87\n" +
                "YXX)B4B\n" +
                "CLQ)S8N\n" +
                "JGW)H99\n" +
                "WHC)SJL\n" +
                "XMH)V5P\n" +
                "VP8)BLG\n" +
                "BCK)R55\n" +
                "4PC)Q1T\n" +
                "TBV)N23\n" +
                "B66)JMZ\n" +
                "YLV)TNS\n" +
                "88G)4C6\n" +
                "RLT)Q76\n" +
                "RRS)WXZ\n" +
                "43D)WQR\n" +
                "ZR3)HDY\n" +
                "S2D)QQX\n" +
                "DTC)BJR\n" +
                "Q3X)YP6\n" +
                "7QH)PWH\n" +
                "WXJ)329\n" +
                "SCK)1GQ\n" +
                "QKG)GSV\n" +
                "ZHJ)HKT\n" +
                "BML)CY5\n" +
                "WFJ)46L\n" +
                "TLH)36T\n" +
                "VC9)QY2\n" +
                "2CF)NFM\n" +
                "Z4B)VYK\n" +
                "46L)5KV\n" +
                "GCH)X1H\n" +
                "14D)3DL\n" +
                "PD6)QZV\n" +
                "34L)LHS\n" +
                "X8Y)9HW\n" +
                "QF5)KB9\n" +
                "24D)WXB\n" +
                "GVR)D8W\n" +
                "PCY)PJK\n" +
                "1QW)L48\n" +
                "J5L)LKS\n" +
                "ZQ9)JPX\n" +
                "L9K)V7K\n" +
                "X4V)4ZR\n" +
                "SB7)8H6\n" +
                "VF3)HHD\n" +
                "2WR)QTH\n" +
                "PPH)W66\n" +
                "C23)ZKT\n" +
                "HGM)XDC\n" +
                "NS6)8GQ\n" +
                "X58)991\n" +
                "MLX)S3N\n" +
                "ZCB)14K\n" +
                "29Q)5SD\n" +
                "BH4)7D3\n" +
                "FVK)NPP\n" +
                "Y9X)N2Q\n" +
                "GH2)R79\n" +
                "HJ2)739\n" +
                "WXS)B66\n" +
                "SY4)59D\n" +
                "F2K)NTK\n" +
                "HHD)35W\n" +
                "935)4NJ\n" +
                "ZKT)C7M\n" +
                "V2D)C9K\n" +
                "HD6)2D9\n" +
                "B98)SCK\n" +
                "ZF6)7J4\n" +
                "PVN)L7Q\n" +
                "SBM)F77\n" +
                "3H8)29Q\n" +
                "F2D)W41\n" +
                "FLH)QV6\n" +
                "YT8)S99\n" +
                "GBQ)YT8\n" +
                "WXZ)6MS\n" +
                "C5W)WFB\n" +
                "KV2)66Y\n" +
                "TBR)L5P\n" +
                "NL6)3SR\n" +
                "SK6)ZCJ\n" +
                "VYY)P54\n" +
                "2L3)GV4\n" +
                "K1X)ZS2\n" +
                "7D3)Z4B\n" +
                "384)457\n" +
                "8R2)TGF\n" +
                "ZB8)CC7\n" +
                "KS8)TYB\n" +
                "RKB)2YT\n" +
                "K1H)XXJ\n" +
                "52W)S2D\n" +
                "WF9)P61\n" +
                "WP9)GG3\n" +
                "95M)8BB\n" +
                "W53)CP6\n" +
                "CM6)R25\n" +
                "GTK)TZM\n" +
                "Q28)D68\n" +
                "WC8)VD3\n" +
                "JMG)KCW\n" +
                "9HW)JFH\n" +
                "9HY)92T\n" +
                "8GQ)6KS\n" +
                "62Z)9WY\n" +
                "VRJ)81G\n" +
                "TGL)VLN\n" +
                "TGF)ZSL\n" +
                "XW6)XJS\n" +
                "TNL)XYQ\n" +
                "9G9)PQJ\n" +
                "VYK)4JY\n" +
                "GMZ)PQ1\n" +
                "NJK)L58\n" +
                "XF8)JVM\n" +
                "GQ2)GVR\n" +
                "N2Q)XKQ\n" +
                "SM4)TQR\n" +
                "C4S)QVC\n" +
                "Q76)LV6\n" +
                "FMH)3D6\n" +
                "7B8)C4S\n" +
                "VYY)2KZ\n" +
                "9L5)27F\n" +
                "7FJ)T99\n" +
                "GY4)JGW\n" +
                "YYQ)WFY\n" +
                "GV4)CRJ\n" +
                "457)VSM\n" +
                "7G3)1P9\n" +
                "SKH)DYN\n" +
                "4PK)9J3\n" +
                "7S9)C22\n" +
                "1KS)V6H\n" +
                "YVS)N4X\n" +
                "2YT)F4V\n" +
                "4ZZ)ZBG\n" +
                "FVM)PYX\n" +
                "8BB)1QW\n" +
                "PQ1)TCV\n" +
                "NR4)5SX\n" +
                "9WY)95M\n" +
                "SPK)DC8\n" +
                "W3D)VB3\n" +
                "L93)3LK\n" +
                "K9J)C9N\n" +
                "4C6)MRG\n" +
                "P5D)5XS\n" +
                "4XY)HF2\n" +
                "MFS)64G\n" +
                "T33)R3T\n" +
                "SFB)TV7\n" +
                "78Q)FYL\n" +
                "892)GK1\n" +
                "GG2)N1F\n" +
                "LTD)XF4\n" +
                "5WX)NQY\n" +
                "QNF)T33\n" +
                "CYJ)6VH\n" +
                "NTG)MFS\n";

        String[] lines = input.split("\n");

        HashMap<String, String> graph = new HashMap<>();

        for (String line: lines) {
            graph.put(line.split("\\)")[1], line.split("\\)")[0]);
        }

        int sum = 0;

        for (Map.Entry<String, String> entry : graph.entrySet()) {
            sum += orbitCount(graph, entry.getKey());
        }

        List<String> orbitsSanta = new ArrayList<>();
        List<String> orbitsMe = new ArrayList<>();

        orbitsSanta = orbitListRecur(graph, "SAN", orbitsSanta);
        orbitsMe = orbitListRecur(graph, "YOU", orbitsMe);

        ArrayList<String> commonOrbits = new ArrayList<>(orbitsMe);

        commonOrbits.retainAll(orbitsSanta);


        System.out.println(orbitRecur(graph, "YOU", 0));
        System.out.println(orbitRecur(graph, "SAN", 0));

        System.out.println(orbitsMe);
        System.out.println(orbitsSanta);
        System.out.println(commonOrbits.size());
        System.out.println("*********");

        System.out.println( (orbitsMe.size() - commonOrbits.size()) + (orbitsMe.size() - commonOrbits.size()) - 1 );

        //331 too high *** 330 too high *** 329 too high

    }

    public static int orbitRecur(Map<String,String> graph, String currentNode, int orbitCounter){
        if(currentNode.equals("COM")) return orbitCounter;
        return orbitRecur(graph, graph.get(currentNode), orbitCounter + 1);
    }

    public static int orbitCount(Map<String,String> graph, String node){
        return orbitRecur(graph, node, 0);
    }

    public static List<String> orbitListRecur(Map<String,String> graph, String currentNode, List<String> orbits){
        if(currentNode.equals("COM")) return orbits;
        orbits.add(currentNode);
        return orbitListRecur(graph, graph.get(currentNode), orbits);
    }
}
